//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestTask.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        internal static string Chest {
            get {
                return ResourceManager.GetString("Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest with number.
        /// </summary>
        internal static string ChestWithNumber {
            get {
                return ResourceManager.GetString("ChestWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Console Input.
        /// </summary>
        internal static string ConsoleInput {
            get {
                return ResourceManager.GetString("ConsoleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of chests you want to create .
        /// </summary>
        internal static string CreateChest {
            get {
                return ResourceManager.GetString("CreateChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want to create the chances for the chests?.
        /// </summary>
        internal static string CreateMethod {
            get {
                return ResourceManager.GetString("CreateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doesn&apos;t exist.
        /// </summary>
        internal static string DoesntExist {
            get {
                return ResourceManager.GetString("DoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter chance in percents of.
        /// </summary>
        internal static string EnterChance {
            get {
                return ResourceManager.GetString("EnterChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found. File with dummy data was created.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please try again..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is opened!.
        /// </summary>
        internal static string IsOpened {
            get {
                return ResourceManager.GetString("IsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. JSON Input.
        /// </summary>
        internal static string JsonInput {
            get {
                return ResourceManager.GetString("JsonInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of the chest you want to open.
        /// </summary>
        internal static string OpenChest {
            get {
                return ResourceManager.GetString("OpenChest", resourceCulture);
            }
        }
    }
}
